require.paths.unshift(".")
require.paths.unshift("./vendor/express/lib")
require.paths.unshift("./vendor/express/lib/support/ext/lib")
require.paths.unshift("./vendor/redis-node-client")
require.paths.unshift("./vendor/riak-js/lib")
require.paths.unshift("./vendor/hashlib/build/default")
